
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import *
from turtle import width
from Btcbf import main

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("513x312")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 312,
    width = 513,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_text(
    110.0,
    31.0,
    anchor="nw",
    text="Welcome to BTCFB",
    fill="#000000",
    font=("Roboto", 12 * -1)
)

canvas.create_text(
    19.0,
    82.0,
    anchor="nw",
    text="About",
    fill="#000000",
    font=("Roboto", 12 * -1)
)

canvas.create_text(
    19.0,
    64.0,
    anchor="nw",
    text="Main",
    fill="#000000",
    font=("Roboto", 12 * -1)
)

canvas.create_rectangle(
    101.0,
    57.0,
    293.0,
    133.0,
    fill="#CACACA",
    outline="")

canvas.create_text(
    105.0,
    64.0,
    anchor="nw",
    text="1.Generate Wallet\n2.Generate Pub key from Priv\n3.Brute Offline mode\n4.Brute Online mode",
    fill="#000000",
    font=("Roboto", 12 * -1)
)

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    439.0,
    57.0,
    image=image_image_1
)

canvas.create_text(
    101.0,
    138.0,
    anchor="nw",
    text="Please enter your choice: ",
    fill="#000000",
    font=("Roboto", 12 * -1)
)

tInput=Entry(window)
tInput.place(x=245, y=138, height=18, width=50)
def getInputBoxValue():
	
    userInput = tInput.get()
    if userInput == "1":
            main("1")
Button(window, text='Start!', bg='#F0F8FF', font=('arial', 8, 'normal'), command=getInputBoxValue).place(x=310, y=138, height=18, width=50)
image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    263.0,
    182.0,
    image=image_image_2
)

canvas.create_rectangle(
    85.0,
    31.0,
    85.0,
    252.0,
    fill="#000000",
    outline="")
window.resizable(False, False)
window.mainloop()
